version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /org.eclipse.m2e.discovery-directory.tests
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /org.eclipse.m2e.discovery.oss
    schedule:
      interval: daily

  - package-ecosystem: maven
    directory: /
    schedule:
      interval: daily
