name: Building and deploying the catalog

on:
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write  # for marvinpinto/action-automatic-releases to generate pre-release
    runs-on: ubuntu-latest

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@03bee3930647ebbf994244c21ddbc0d4933aab4f # v2.3.0
      with:
        egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

    - name: Checkout sources
      uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0

    - name: Set up JDK 1.8
      uses: actions/setup-java@5ffc13f4174014e2d4d4572b3d74c3fa61aeb2c2 # v3.11.0
      with:
        distribution: 'temurin'
        java-version: 8
        cache: 'maven'

    - name: Build with Maven
      run: mvn -B verify --update-snapshots --file pom.xml -PCI

    - name: Deploy p2 update site
      if: github.ref == 'refs/heads/master' && runner.os == 'Linux'
      uses: marvinpinto/action-automatic-releases@d68defdd11f9dcc7f52f35c1b7c236ee7513bcc1 # latest
      with:
        repo_token: "${{secrets.GITHUB_TOKEN}}"
        automatic_release_tag: "2.x"
        title: "m2e catalog"
        files: |
          org.eclipse.m2e.discovery.oss/target/*.jar
          org.eclipse.m2e.discovery.oss/target/classes/catalogs/*.xml